2020-10-28 23:15:44,258 INFO    MainThread:10643 [wandb_init.py:_log_setup():293] Logging user logs to wandb/run-20201028_231544-68cmyi7k/logs/debug.log
2020-10-28 23:15:44,258 INFO    MainThread:10643 [wandb_init.py:_log_setup():294] Logging internal logs to wandb/run-20201028_231544-68cmyi7k/logs/debug-internal.log
2020-10-28 23:15:44,258 INFO    MainThread:10643 [wandb_setup.py:_flush():69] setting env: {}
2020-10-28 23:15:44,258 INFO    MainThread:10643 [wandb_setup.py:_flush():69] setting user settings: {'email': 'mnqjng@gmail.com'}
2020-10-28 23:15:44,258 INFO    MainThread:10643 [wandb_setup.py:_flush():69] multiprocessing start_methods=spawn,fork,forkserver
2020-10-28 23:15:45,263 INFO    MainThread:10643 [wandb_run.py:_console_start():1290] atexit reg
2020-10-28 23:15:45,264 INFO    MainThread:10643 [wandb_run.py:_redirect():1160] redirect: SettingsConsole.REDIRECT
2020-10-28 23:15:45,264 INFO    MainThread:10643 [wandb_run.py:_redirect():1163] Redirecting console.
2020-10-28 23:15:45,264 INFO    MainThread:10643 [redirect.py:install():196] install start
2020-10-28 23:15:45,264 INFO    MainThread:10643 [redirect.py:install():211] install stop
2020-10-28 23:15:45,264 INFO    MainThread:10643 [redirect.py:install():196] install start
2020-10-28 23:15:45,265 INFO    MainThread:10643 [redirect.py:install():211] install stop
2020-10-28 23:15:45,265 INFO    MainThread:10643 [wandb_run.py:_redirect():1207] Redirects installed.
2020-10-28 23:17:06,263 ERROR   stdout    :10643 [redirect.py:_pipe_relay():129] problem in pipe relay
Traceback (most recent call last):
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/lib/redirect.py", line 127, in _pipe_relay
    cb(name, data)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 644, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 429, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2020-10-28 23:17:07,213 INFO    MainThread:10643 [wandb_run.py:_atexit_cleanup():1263] got exitcode: 1
2020-10-28 23:17:07,213 INFO    MainThread:10643 [wandb_run.py:_restore():1235] restore
2020-10-28 23:17:07,213 INFO    MainThread:10643 [redirect.py:uninstall():215] uninstall start
2020-10-28 23:17:07,213 ERROR   stderr    :10643 [redirect.py:_pipe_relay():129] problem in pipe relay
Traceback (most recent call last):
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/lib/redirect.py", line 127, in _pipe_relay
    cb(name, data)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 644, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/Users/minqijiang/miniconda3/envs/auto-drac/lib/python3.8/site-packages/wandb/interface/interface.py", line 429, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2020-10-28 23:17:07,214 INFO    MainThread:10643 [redirect.py:_stop():264] _stop: stdout
2020-10-28 23:17:07,214 INFO    MainThread:10643 [redirect.py:_stop():270] _stop closed: stdout
2020-10-28 23:17:07,214 INFO    stdout    :10643 [redirect.py:_pipe_relay():119] relay done saw last write: stdout
2020-10-28 23:17:07,214 INFO    stdout    :10643 [redirect.py:_pipe_relay():135] relay done done: stdout
2020-10-28 23:17:07,214 INFO    MainThread:10643 [redirect.py:_stop():276] _stop joined: stdout
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:_stop():278] _stop rd closed: stdout
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:uninstall():219] uninstall done
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:uninstall():215] uninstall start
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:_stop():264] _stop: stderr
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:_stop():270] _stop closed: stderr
2020-10-28 23:17:07,215 INFO    stderr    :10643 [redirect.py:_pipe_relay():119] relay done saw last write: stderr
2020-10-28 23:17:07,215 INFO    stderr    :10643 [redirect.py:_pipe_relay():135] relay done done: stderr
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:_stop():276] _stop joined: stderr
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:_stop():278] _stop rd closed: stderr
2020-10-28 23:17:07,215 INFO    MainThread:10643 [redirect.py:uninstall():219] uninstall done
2020-10-28 23:17:07,216 INFO    MainThread:10643 [wandb_run.py:_restore():1235] restore
2020-10-28 23:17:08,382 INFO    MainThread:10643 [internal.py:handle_exit():137] Internal process exited
